---
cwd: /var/rails/badi2010/current
user: kreba
group: kreba
environment: production
address: 127.0.0.1
port: '8000'
servers: 2
pid_file: /var/rails/badi2010/shared/pids/mongrel.pid
log_file: /var/rails/badi2010/shared/log/mongrel.log